blog/urls.py
from django.urls import path
from . import views
app_name = "blog"

urlpatterns = [
    path("",views.blog_list,name="blog_list"),
    path("<int:id>",views.blog_detail,name="blog_detail"),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path , include
# from django.conf import settings
from django.conf.urls.static import static
from restaurant import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foods.urls')),
    path('reservation/', include('reservation.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

blog/models.py
from distutils.command.upload import upload
from email.mime import image
import imp
from importlib.resources import contents
from tabnanny import verbose
from tkinter import CASCADE
from unicodedata import category
from django.db import models
from django.forms import ImageField
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

# Create your models here.

class Blog(models.Model):
    class Meta:
        verbose_name= "بلاگ"
        verbose_name_plural = 'بلاگ'
    title = models.CharField(_("عنوان"),max_length=50)
    description = models.CharField(_("توضیحات"),max_length=100)
    content = models.TextField(_("متن"))
    created_at = models.DateTimeField(_("زمان انتشار"),default=timezone.now)
    author = models.ForeignKey(User,verbose_name=_("نویسنده"),on_delete=models.CASCADE)
    image = models.ImageField(_("تصویر"),upload_to="blogs/",null = True)
    tags = models.ManyToManyField("Tag",verbose_name=_("تگ ها"),related_name="blogs",blank=True,null=True) 
    category = models.ForeignKey("Category",related_name="blog",verbose_name=_("دسته بندی"), on_delete=models.CASCADE,blank=True,null=True)
    def __str__(self):
        return self.title

class Category(models.Model):
    class Meta:
        verbose_name= "دسته بندی"
        verbose_name_plural = 'دسته بندی'

    title = models.CharField(_("عنوان"),max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"),auto_now=False,auto_now_add=True)

    def __str__(self):
        return self.title

class Tag(models.Model):
    class Meta:
        verbose_name= "تگ"
        verbose_name_plural = 'تگ'
    title = models.CharField(_("عنوان"), max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"),auto_now=False,auto_now_add=True)
    update_at = models.DateTimeField(_("تاریخ بروز رسانی"),auto_now=True,auto_now_add=False)
    def __str__(self):
        return self.title

blog/views.py
from multiprocessing import context
from unicodedata import category
from django.shortcuts import render
from . models import Blog , Tag , Category

# Create your views here.

def blog_list(request):
    blogs = Blog.objects.all()
    
    context = {
        "blogs":blogs,
    }

    return render(request,"blog/blog_list.html",context)

def blog_detail(request,id):
    blog = Blog.objects.get(id=id)
    tags = Tag.objects.all().filter(blogs=blog)
    recents = Blog.objects.all().order_by("-created_at")[:5]
    categories = Category.objects.all()
    context = {
        "blog":blog,
        "tags":tags,
        "recents":recents,
        "categories":categories,
    }
    return render(request,"blog/blog_detail.html",context)

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Blog</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog details -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>{{blog.title}}</h2>
						<p>{{blog.description}}</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xl-8 col-lg-8 col-12">
					<div class="blog-inner-details-page">
						<div class="blog-inner-box">
							<div class="side-blog-img">
								<img class="img-fluid" src="{{blog.image.url}}" style="width: 700px;" alt="">							
								<div class="date-blog-up">
									{{blog.created_at|date:"Y m d"}}
								</div>
							</div>
							<div class="inner-blog-detail details-page">
								<h3>{{blog.description}}</h3>
								<ul>
									<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.author}}</span></li>
									<li>|</li>
									<li><i class="zmdi zmdi-time"></i>Time : <span>{{blog.created_at.time}}</span></li>
								</ul>
								<p dir="rtl">{{blog.content}}</p>
								
							</div>
						</div>

					</div>
				</div>
			
				<div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
					<div class="right-side-blog">
						
						<h3>Categories</h3>
						<div class="blog-categories">
							<ul>
                                {% for cat in categories %}
								<li><a href="#"><span>{{cat.title}}</span></a></li>
                                {% endfor %}
							</ul>
						</div>
						<h3>Recent Post</h3>
						<div class="post-box-blog">
							<div class="recent-post-box">
                                {% for blog in recents %}
								<div class="recent-box-blog">
									<div class="recent-img">
										<img class="img-fluid" src="{{blog.image.url}}" style="height: 70px;width: 70px;" alt="">
									</div>
									<div class="recent-info">
										<ul>
											<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.author}}</span></li>
											<li>|</li>
											<li><i class="zmdi zmdi-time"></i>Time : <span>{{blog.created_at|date:"Y m d"}}</span></li>
										</ul>
										<h4>{{blog.description}}</h4>
									</div>
								
                                
                                
                                </div>
                                {% endfor %}
							</div>
						</div>
						<h3>Recent Tag</h3>
						<div class="blog-tag-box">
							<ul class="list-inline tag-list">
                                {% for tag in tags %}
								<li class="list-inline-item"><a href="#">{{tag.title}}</a></li>
                                {% endfor %}
							</ul>
						</div>
					</div>
				</div>
			
			</div>
		</div>
	</div>
	<!-- End details -->
	

	
{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Blog</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>Blog</h2>
						<p>Read and enjoy yourself with our restaurant posts. </p>
					</div>
				</div>
			</div>
			<div class="row">
				{% for blog in blogs %}
                <div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="{{blog.image.url}}" style="height: 430px;" alt="">
						</div>
						<div class="blog-detail">
							<h4>{{blog.title}}</h4>
							<ul>
								<li><span>Posted By {{blog.author}}</span></li>
								<li>|</li>
								<li><span>{{blog.created_at|date:"Y m d"}}</span></li>
							</ul>
							<p>{{blog.content|truncatewords:60}}</p>
							
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'blog:blog_detail' blog.id %}">Read more</a>
						</div>
					</div>
				</div>
                {% endfor %}

			</div>
		</div>
	</div>
	<!-- End blog -->
	

{% endblock content %}